#ifndef MMPI2_HPP
#define MMPI2_HPP

#include <String>

namespace MMPI2
{
    enum Q_VAR
    {
        Q_QUESTIONS = 567,  // 567
        Q_SCALES    = 18,
        Q_VRIN      = 67,
        Q_TRIN1     = 13,
        Q_TRIN2     = 10,
        Q_NORMS     = 200, // ???
        TRUE_INT    = 1,
        FALSE_INT   = 0
    };

    enum SCALES {F,FB,FP,FBS,L,K,S,HS,D,HY,PD,MFM,MFF,PA,PT,SC,MA,SI};

    class Calc
    {
        public:
            Calc();
            virtual ~Calc();
            bool raw_answers[Q_QUESTIONS];
            int scales_result[Q_SCALES];
            int trin_result;
            int vrin_result;
    };

    // [2]: 0 - PRAWDA, 1 - FAŁSZ
    const unsigned short int m_scales[Q_SCALES][2][Q_QUESTIONS] =
    {
        {{11,18,24,36,42,54,59,68,72,84,96,97,114,138,144,150,162,180,182,198,228,234,240,246,252,258,270,282,287,294,31,2,324,336,355,361},
         {2,6,29,75,76,78,81,90,93,102,108,120,139,142,183,186,192,203,204,210,260,276,318,330,343}},
        {{281,291,303,311,319,322,323,327,329,332,333,380,387,407,431,450,468,476,478,484,489,503,506,511,515,516,51,7,520,524,526,530,540,544,546,549,551,555},
         {383,404,501}},
        {{36,96,114,144,162,198,270,282,291,294,319,322,336,355,478,530,555},
         {76,81,88,102,108,110,120,192,276,343}},
        {{11,18,28,30,31,39,40,44,59,111,252,274,325,339,464,469,505,506},
         {12,41,57,58,81,110,117,152,164,176,224,227,248,249,250,255,264,284,362,373,374,419,433,496,561}},
        {{},
         {16,29,41,51,77,93,102,107,123,139,153,183,203,232,260}},
        {{83},
         {29,37,58,76,110,116,122,127,130,136,148,157,158,167,171,196,213,243,267,284,290,330,338,339,341,346,348,356,365}},
        {{121,148,184,194,534,560},
         {15,50,58,76,81,87,89,104,110,120,123,154,196,205,213,225,264,279,284,290,302,337,341,346,352,373,374,403,420,423,428,430,433,442,445,449,461,486,487,523,538,542,545,547}},
        {{18,28,39,53,59,97,101,111,149,175,247},
         {2,3,8,10,20,45,47,57,91,117,141,143,152,164,173,176,179,208,224,249,255}},
        {{5,15,18,31,38,39,46,56,73,92,117,127,130,146,147,170,175,181,215,233},
         {2,9,10,20,29,33,37,43,45,49,55,68,75,76,95,109,118,134,140,141,142,143,148,165,178,188,189,212,221,223,226,238,245,248,260,267,330}},
        {{11,18,31,39,40,44,65,101,166,172,175,218,230},
         {2,3,7,8,9,10,14,26,29,45,47,58,76,81,91,95,98,110,115,116,124,125,129,135,141,148,151,152,157,159,161,164,167,173,176,179,185,193,208,213,224,241,243,249,253,263,265}},
        {{17,21,22,31,32,35,42,52,54,56,71,82,89,94,99,105,113,195,202,219,225,259,264,288},
         {9,12,34,70,79,83,95,122,125,129,143,157,158,160,167,171,185,209,214,217,226,243,261,263,266,267}},
        {{4,25,62,64,67,74,80,112,119,122,128,137,166,177,187,191,196,205,209,219,236,251,256,268,271},
         {1,19,26,27,63,68,69,76,86,103,104,107,120,121,132,133,163,184,193,194,197,199,201,207,231,235,237,239,254,257,272}},
        {{4,25,62,64,67,74,80,112,119,121,122,128,137,177,187,191,196,205,219,236,251,256,271},
         {1,19,26,27,63,68,69,76,86,103,104,107,120,132,133,163,166,184,193,194,197,199,201,207,209,231,235,237,239,254,257,268,272}},
        {{16,17,22,23,24,42,99,113,138,144,145,146,162,234,259,271,277,285,305,307,333,334,336,355,361},
         {81,95,98,100,104,110,244,255,266,283,284,286,297,314,315}},
        {{11,16,23,31,38,56,65,73,82,89,94,130,147,170,175,196,218,242,273,275,277,285,289,301,302,304,308,309,310,313,316,317,320,325,326,327,328,329,331},
         {3,9,33,109,140,165,174,293,321}},
        {{16,17,21,22,23,31,32,35,38,42,44,46,48,65,85,92,138,145,147,166,168,170,180,182,190,218,221,229,233,234,242,247,252,256,268,273,274,277,279,281,287,291,292,296,298,299,303,307,311,316,319,320,322,323,325,329,332,333,355},
         {6,9,12,34,90,91,106,165,177,179,192,210,255,276,278,280,290,295,343}},
        {{13,15,21,23,50,55,61,85,87,98,113,122,131,145,155,168,169,182,190,200,205,206,211,212,218,220,227,229,238,242,244,248,250,253,269},
         {88,93,100,106,107,136,154,158,167,243,263}},
        {{31,56,70,100,104,110,127,135,158,161,167,185,215,243,251,265,275,284,289,296,302,308,326,328,337,338,347,348,351,352,357,358,364,367,368,369},
         {25,32,49,79,86,106,112,131,181,189,207,209,231,237,255,262,267,280,321,335,340,342,344,345,350,353,354,359,360,362,363,366,370}},
    };

    const unsigned short int m_vrin[Q_VRIN][4] =
    {
        {22,1,277,0}, {103,1,344,0}, {226,1,267,0}, {365,1,452,0},
        {28,1,111,0}, {103,0,344,1}, {246,1,407,0}, {372,1,405,0},
        {28,0,111,1}, {105,0,431,1}, {259,0,333,1}, {395,1,435,0},
        {31,1,299,0}, {116,0,430,1}, {265,0,337,1}, {396,1,403,0},
        {32,0,316,1}, {135,0,482,1}, {271,1,285,0}, {397,1,438,0},
        {46,1,265,0}, {136,0,302,1}, {277,0,306,1}, {411,0,485,1},
        {49,1,280,0}, {144,1,336,0}, {290,0,556,1}, {413,1,449,0},
        {60,0,311,1}, {146,1,532,0}, {302,1,444,0}, {413,0,449,1},
        {65,1,305,0}, {147,1,325,0}, {303,0,506,1}, {435,0,555,1},
        {71,0,454,1}, {147,0,325,1}, {323,1,324,0}, {472,1,533,0},
        {73,0,377,1}, {161,1,289,0}, {323,0,324,1}, {489,1,502,0},
        {84,1,105,0}, {166,1,268,0}, {331,0,442,1}, {491,1,509,0},
        {86,0,359,1}, {175,0,464,1}, {339,0,394,1}, {506,1,520,0},
        {95,0,388,1}, {180,1,316,0}, {349,0,515,1}, {513,1,542,0},
        {96,1,311,0}, {192,1,276,0}, {350,0,521,1}, {533,0,565,1},
        {99,1,138,0}, {196,0,415,1}, {353,0,370,1}, {539,1,554,0},
        {99,0,138,1}, {199,0,467,1}, {364,0,554,1}
    };

    // TRIN1 - pary tylko dla wartosci PRAWDA
    const unsigned short int m_trin1[Q_TRIN1][2] =
    {
        {6,478}, {62,272}, {141,464}, {318,450}, {12,166}, {91,247}, {167,342}, {40,224}, {95,303}, {209,351}, {53,208}, {99,314}, {261,471}
    };

    // TRIN2 - pary tylko dla wartosci FALSZ
    const unsigned short int m_trin2[Q_TRIN2][2] =
    {
        {9,56}, {75,303}, {265,353}, {405,444}, {49,167}, {165,472}, {273,561}, {73,239}, {262,275}, {306,383}
    };

    const unsigned short int m_norms[Q_SCALES][Q_NORMS] =
    {
        {9,56}, {75,303}, {265,353}, {405,444}, {49,167}, {165,472}, {273,561}, {73,239}, {262,275}, {306,383}
    };

    const std::string trin_name = "TRIN - Skala Niespójności Odpowiedzi Zgodnych";
    const std::string vrin_name = "VRIN - Skala Niespójności Odpowiedzi Niezgodnych";

    const std::string scales_names[Q_SCALES] =
    {
        "F - Skala Odpowiedzi Rzadkich",
        "FB - Skala Odpowiedzi Rzadkich dla dalszej części testu",
        "FP - Skala Odpowiedzi Rzadkich dotycząca objawów psychopatologicznych",
        "FBS - Skala wyolbrzymianie Symptomów",
        "L - Skala Kłamstwa",
        "K - Skala Korekcyjna",
        "S - Skala Pozytywnej Autoprezentacji",
        "Hs - Skala Hipochondrii",
        "D - Skala Depresji",
        "Hy - Skala Histerii",
        "Pd - Skala Odchyleń Psychopatycznych",
        "Mf-m - Skala Męskości-Kobiecości (Mężczyźni)",
        "Mf-f - Skala Męskości-Kobiecości (Kobiety)",
        "Pa - Skala Paranoi",
        "Pt - Skala Psychastenii",
        "Sc - Skala schizofrenii",
        "Ma - Skala Hipomanii",
        "Si - Skala Introwersji Społecznej"
    };

    const std::string questions[Q_QUESTIONS] =
    {
        "Lubię czasopisma techniczne.",
        "Mam dobry apetyt.",
        "Rano przeważnie budzę się świeży/świeża i wypoczęty/wypoczęta.",
        "Myślę, że podobałaby mi się praca bibliotekarza.",
        "Hałas łatwo mnie budzi.",
        "Moj ojciec jest dobrym człowiekiem lub (jeśli twój ojciec nie żyje): Mój ojciec był dobrym człowiekiem.",
        "Lubię czytać w gazetach artykuły na temat przestępstw.",
        "Moje dłonie i stopy są zazwyczaj wystarczająco ciepłe.",
        "Moje codzienne życie jest pełne spraw, które mnie interesują.",
        "Jestem tak zdolny/zdolna do pracy, jak zawsze.",
        "Przeważnie wydaje mi się, ze mam ściśnięte gardło.",
        "Moje życie seksualne jest satysfakcjonujące.",
        "Ludzie powinni starać się zrozumieć swoje sny i czerpać z nich wskazówki lub przestrogi.",
        "Lubię powieści kryminalne lub detektywistyczne.",
        "Pracuję pod dużą presją.",
        "Czasami myślę rzeczach zbyt złych,  aby o nich mówić.",
        "Jestem przekonany/przekonana, że życie mnie nie rozpieszcza.",
        "Dokuczają mi napady mdłości i torsji.",
        "Kiedy podejmuję nową pracę, lubię dowiedzieć się, dla kogo trzeba być miłym.",
        "Bardzo rzadko dokuczają mi zaparcia.",
        "Czasami miałem/miałam wielką ochotę wyprowadzić się z domu.",
        "Chyba nikt mnie nie rozumie.",
        "Czasami miewam niekontrolowane ataki śmiechu i płaczu.",
        "Czasami biorą mnie we władanie złe moce.",
        "Chciałbym/chciałabym być piosenkarzem/piosenkarką.",
        "Kiedy mam kłopoty, czuję, że najlepiej jest nic nie mówić.",
        "Kiedy ludzie wyrządzają mi krzywdę, czuję, że powinienem/powinnam im w miarę możności odpłacić, choćby dla zasady.",
        "Kilka razy w tygodniu nękają mnie problemy żołądkowe.",
        "Czasami mam ochotę przeklinać.",
        "Co kilka nocy mam złe sny.",
        "Trudno mi się skupić na zadaniu lub pracy.",
        "Miałem/miałam bardzo osobliwe i dziwne doświadczenia.",
        "Rzadko martwię się swoje zdrowie.",
        "Nigdy nie miałem/nie miałam kłopotów z powodu swoich zachowań seksualnych.",
        "Kiedy byłem/byłam młody/młoda, czasami cos kradłem/kradłam.",
        "Prawie stałe mam kaszel.",
        "Czasami mam ochotę coś roztrzaskać.",
        "Bywały dni, tygodnie czy miesiące, gdy o nic nie dbałem, bo nie mogłem/nie mogłam się do niczego zabrać.",
        "Mój sen jest niespokojny i przerywany.",
        "Często mam wrażenie, że boli mnie cała głowa.",
        "Nie zawsze mówię prawdę.",
        "Gdyby ludzie się na mnie nie uwzięli, mógłbym/mogłabym odnosić większe sukcesy.",
        "Moja ocena sytuacji jest teraz bardziej trafna niż kiedykolwiek.",
        "Raz w tygodniu lub częściej, nagle, bez żadnego powodu robi mi się gorąco.",
        "Moje zdrowie fizyczne jest równie dobre, jak większości moich znajomych.",
        "Wolę minąć bez słowa kolegów ze szkoły lub znajomych, których długo nie widziałem/nie widziałam, chyba że odezwą się do mnie pierwsi.",
        "Prawie nigdy nie dokuczają mi bóle serca czy klatki piersiowej.",
        "Na ogół wolałbym/wolałabym siedzieć i marzyć niż robić cokolwiek innego.",
        "Jestem bardzo towarzyską osobą.",
        "Często musiałem/musiałam wykonywać polecenia kogoś, kto nie wiedział tak dużo jak ja.",
        "Nie czytam codziennie artykułów wstępnych w gazecie.",
        "Nie żyłem/nie żyłam tak, jak należy.",
        "Często czuję w pewnych częściach ciała pieczenie, mrowienie, drętwienie lub ociężałość.",
        "Mojej rodzinie nie podoba się zawód, który wybrałem/wybrałam (lub zawód, który mam zamiar wybrać na całe życie).",
        "Czasami tak się czegoś uczepię, że inni tracą do mnie cierpliwość.",
        "Żałuję, że nie potrafię być tak szczęśliwy/szczęśliwa, jak inni.",
        "Prawie nigdy nie odczuwam bólu w karku.",
        "Myślę, że mnóstwo ludzi wyolbrzymia swoje nieszczęścia, aby uzyskać od innych współczucie i pomoc.",
        "Co kilka dni lub częściej dokucza mi ściskanie w dołku.",
        "Kiedy jestem z ludźmi, niepokoi mnie, że słyszę bardzo dziwne rzeczy.",
        "Jestem ważną osobą.",
        "Często żałowałem, że nie jestem dziewczyną lub (jeśli jesteś dziewczyną): Nigdy nie żałowałam, ze jestem dziewczyną.",
        "Niełatwo zranić moje uczucia.",
        "Lubię czytać romanse.",
        "Przeważnie czuję smutek.",
        "Byłoby lepiej, gdyby skasowano większość przepisów prawnych.",
        "Lubię poezję.",
        "Czasami drażnię zwierzęta.",
        "Myślę, że lubiłbym/lubiłabym pracę strażnika leśnego.",
        "Łatwo mnie pokonać w sporze.",
        "Ostatnio tracę nadzieję, że do czegoś dojdę.",
        "Moja dusza czasami opuszcza ciało.",
        "Zdecydowanie brakuje mi pewności siebie.",
        "Chciałbym/chciałabym być kwiaciarzem/kwiaciarką.",
        "Przeważnie czuję, że warto żyć.",
        "Na ogół trzeba wielu argumentów, żeby przekonać ludzi do prawdy.",
        "Zdarza mi się, że odkładam do jutra to, co powinienem/powinnam zrobić dziś.",
        "Jestem lubiany/lubiana przez większość osób, które mnie znają.",
        "Nie przejmuję się, kiedy ktoś ze mnie żartuje.",
        "Chciałbym/chciałabym być pielęgniarzem/pielęgniarką.",
        "Sądzę, że większość ludzi gotowa jest skłamać, aby uzyskać przewagę.",
        "Robię wiele rzeczy, których potem żałuję (wydaje się, ze żałuję częściej niż inni).",
        "Bardzo rzadko kłócę się z członkami mojej rodziny.",
        "Co najmniej raz zawieszono mnie w prawach ucznia za złe zachowanie.",
        "Czasami odczuwam silne pragnienie, żeby zrobić cos złego lub szokującego.",
        "Lubię chodzić na przyjęcia i inne imprezy, na których jest głośna zabawa.",
        "Znajdowałem/znajdowałam się w sytuacjach tak pełnych możliwości, że nie byłem/nie byłam w stanie dokonać wyboru.",
        "Uważam, że kobiety powinny mieć tyle samo swobody seksualnej, co mężczyźni.",
        "Najcięższe boje toczę z samym/samą sobą.",
        "Kocham swojego ojca lub (jeśli twój ojciec nie żyje): Kochałem/kochałam swojego ojca.",
        "Bardzo rzadko dokuczają mi skurcze lub drżenie mięśni, albo nie odczuwam tego wcale.",
        "Nie wydaje się, żebym dbał/dbała o to, co się ze mną dzieje.",
        "Kiedy coś mi dolega, bywam czasami rozdrażniony/rozdrażniona.",
        "Często czuję się tak, jakbym zrobił/zrobiła coś niewłaściwego lub złego.",
        "Przeważnie jestem szczęśliwy/szczęśliwa.",
        "Widzę wokół siebie przedmioty, zwierzęta lub ludzi, których inni nie widzą.",
        "Prawie stałe mam rozsadzania w głowie lub nosie.",
        "Niektórzy ludzie są tak apodyktyczni, że mam ochotę robić im na przekór, nawet jeśli wiem, że mają rację.",
        "Ktoś się na mnie uwziął.",
        "Nigdy nie zrobiłem/nie zrobiłam niczego niebezpiecznego tylko po to, by poczuć dreszcz emocji.",
        "Często mam wrażenie, jakby wokół mojej głowy była ciasna obręcz.",
        "Czasami złoszczę się.",
        "Wyścig lub gra sprawiają mi większą przyjemność, jeśli obstawiam wynik.",
        "Ludzie są przeważnie uczciwi głównie dlatego, że boją się zostać przyłapani.",
        "W szkole wysyłano mnie czasami do dyrektora z powodu złego zachowania.",
        "Moja mowa jest taka sama jak zawsze (nie szybsza, nie wolniejsza, nie bełkotliwa czy ochrypła).",
        "Moje maniery przy stole nie są tak dobre w domu, jak wtedy, gdy jestem w towarzystwie poza domem.",
        "Każdy, kto potrafi i chce ciężko pracować, ma duże szanse na sukces.",
        "Wydaje mi się, że jestem tak zdolny/zdolna i bystry/bystra, jak większość ludzi wokół mnie.",
        "Większość ludzi woli raczej użyć niezbyt uczciwych sposobów do uzyskania korzyści lub przewagi niż je stracić.",
        "Żołądek przysparza mi wielu kłopotów.",
        "Lubię dramaty.",
        "Wiem, kto jest odpowiedzialny za większość moich kłopotów.",
        "Czasami czyjeś rzeczy osobiste, takie jak buty, rękawiczki, itp, tak silnie mnie pociągają, że mam ochotę ich dotykać lub je ukraść, mimo że nie są mi do niczego potrzebne.",
        "Widok krwi nie przeraża mnie ani nie przyprawia o mdłości.",
        "Często nie mogę zrozumieć, dlaczego jestem tak drażliwy/drażliwa i zrzędliwy/zrzędliwa.",
        "Nigdy nie wymiotowałem/nie wymiotowałam krwią ani nie plułem/nie plułam krwią.",
        "Nie przejmuję się tym, że mogę się zarazić jakąś chorobą.",
        "Lubię zbierać kwiaty i hodować rośliny doniczkowe.",
        "Często widzę konieczność, aby stanąć w obronie tego, co uważam za słuszne.",
        "Nigdy nie oddawałem/nie oddawałam się żadnym niezwykłym praktykom seksualnym.",
        "Czasami moje myśli gonią tak szybko, że nie jestem w stanie ich wypowiedzieć.",
        "Gdybym mógł/mogła dostać się do kina bez biletu i miał/miała pewność, że nikt tego nie zauważy, przypuszczalnie bym to zrobił/zrobiła.",
        "Często zastanawiam się, jaki ukryty powód może mieć ktoś, kto robi dla mnie coś miłego.",
        "Sadzę, że moje życie domowe jest równie przyjemne, jak życie większości ludzi, których znam.",
        "Wierzę w egzekwowanie prawa.",
        "Gdy ktoś mnie krytykuje lub karci, strasznie mnie to rani.",
        "Lubię gotować.",
        "Moje postępowanie w dużej mierze zależy od zachowania otaczających mnie ludzi.",
        "Czasem czuję się zupełnie bezużyteczny/bezużyteczna.",
        "Jako dziecko należałem/należałam do grupy przyjaciół, którzy starali się być lojalni wobec siebie we wszystkich trudnych sytuacjach.",
        "Wierzę w życie po śmierci.",
        "Chciałbym/chciałabym być żołnierzem.",
        "Czasami mam ochotę wszcząć z kimś bójkę na pięści.",
        "Często traciłem/traciłam na  tym, że nie potrafiłem/nie potrafiłam podjąć decyzji wystarczająco szybko.",
        "Tracę cierpliwość, gdy ludzie pytają mnie radę lub w inny sposób przerywają mi, kiedy robię coś ważnego.",
        "Kiedyś prowadziłem/prowadziłam pamiętnik.",
        "Uważam, że ktoś przeciwko mnie spiskuje.",
        "W grze wolę raczej wygrać niż przegrać.",
        "Kiedy idę spać, nie trapią mnie na ogół żadne myśli czy wyobrażenia.",
        "W ostatnich latach przeważnie dobrze się czuję.",
        "Nigdy nie miałem/nie miałam ataku padaczki ani drgawek.",
        "Ani nie przybieram, ani nie tracę na wadze.",
        "Uważam, że jestem śledzony/śledzone.",
        "Mam poczucie, że często byłem/byłam karany/karana bez powodu.",
        "Łatwo zbiera mi się na płacz.",
        "Nie rozumiem tego, co czytam, tak dobrze jak dawniej.",
        "Nigdy w życiu nie czułem/nie czułam się lepiej niż teraz.",
        "Czubek mojej głowy jest czasem bardzo wrażliwy.",
        "Czasami czuję potrzebę fizycznego zranienia siebie lub kogoś innego.",
        "Nie znoszę, kiedy ktoś nabiera mnie tak sprytnie, że muszę przyznać, że wyszedłem/wyszłam na głupka.",
        "Nie męczę się szybko.",
        "Lubię znać ważnych ludzi, bo to sprawia, że sam/sama czuję się ważny/ważna.",
        "Boję się patrzeć w dół z wysokości.",
        "Nie zdenerwowałbym się/nie zdenerwowałabym się, gdyby ktoś z mojej rodziny popadł w kłopoty z prawem.",
        "Szczęśliwy/szczęśliwa jestem tylko wtedy, gdy gdzieś wędruję lub podróżuję.",
        "Nie przejmuję się tym, co inni o mnie myślą.",
        "Czułbym/czułabym się niezręcznie, popisując się na imprezie towarzyskiej, nawet gdyby inni robili to samo.",
        "Nigdy nie zemdlałem/nie zemdlałam.",
        "Lubiłem/lubiłam szkołę.",
        "Często muszę się starać, by ukryć swoją nieśmiałość.",
        "Ktoś próbował mnie otruć.",
        "Nie odczuwam zbyt wielkiego strachu przed wężami.",
        "Rzadko miewam zawroty głowy lub nie miewam ich nigdy.",
        "Z moją pamięcią jest chyba wszystko w porządku.",
        "Niepokoją mnie sprawy związane z seksem.",
        "Trudno mi się rozmawia z ludźmi, których dopiero co poznałem/poznałam.",
        "Miewałem/miewałam okresy, kiedy robiłem/robiłam coś, czego później nie pamiętałem/nie pamiętałam.",
        "Kiedy się nudzę, lubię zrobić trochę zamieszania.",
        "Boję się, że postradam rozum.",
        "Jestem przeciwny/przeciwna dawaniu pieniędzy żebrakom?.",
        "Często zauważam, że kiedy próbuję cos robić, drżą mi ręce.",
        "Mogę czytać przez dłuższy czas bez zmęczenia oczu.",
        "Lubię się uczyć i czytać o tym, nad czym pracuję.",
        "Bardzo często czuję się ogólnie osłabiony/osłabiona.",
        "Rzadko miewam bóle głowy.",
        "Moje ręce nie stały się niezgrabne czy niezdarne.",
        "Czasami, kiedy jestem zakłopotany/zakłopotana, oblewam się potem, co bardzo mnie denerwuje.",
        "Nie mam trudności z utrzymaniem równowagi podczas chodzenia.",
        "Coś jest nie w porządku z moim umysłem.",
        "Nie miewam napadów kataru siennego ani astmy.",
        "Miewałem/miewałam ataki, w czasie których nie panowałem/nie panowałam nad swoimi ruchami lub mową, choć wiedziałem/wiedziałam, co się wokół mnie dzieje.",
        "Wśród znanych mi ludzi są tacy, których nie lubię.",
        "Bardzo rzadko oddaję się marzeniom.",
        "Chciałbym/chciałabym nie być tak nieśmiały/nieśmiała.",
        "Nie boję się mieć do czynienia z pieniędzmi.",
        "Gdybym był/była reporterem, bardzo chciałbym/chciałabym zajmować się nowinami teatralnymi.",
        "Lubię wiele różnego rodzaju gier i innych form wypoczynku.",
        "Lubię flirtować.",
        "Moi bliscy traktują mnie bardziej jak dziecko niż osobę dorosłą.",
        "Chciałbym/chciałabym być dziennikarzem.",
        "Moja matka jest dobrą kobietą lub (jeśli twoja matka nie żyje): Moja matka była dobrą kobietą.",
        "Idąc ulicą, bardzo staram się omijać szczeliny między płytami chodnikowymi.",
        "Nigdy nie miałem/nie miałam na skórze żadnych wyprysków, które by mnie zaniepokoiły.",
        "W porównaniu z innymi rodzinami, moja rodzina jest bardzo mało zżyta i jest w niej mało miłości.",
        "Często łapię się na tym, że coś mnie martwi.",
        "Myślę, że podobałaby mi się praca przedsiębiorcy budowlanego.",
        "Często słyszę głosy, których źródła nie znam.",
        "Lubię naukę.",
        "Nie jest mi trudno prosić przyjaciół o pomoc, nawet jeśli nie jestem w stanie się zrewanżować.",
        "Bardzo lubię polowania.",
        "Moi rodzice często mieli zastrzeżenia do osób, wśród których się obracałem/obracałam.",
        "Czasami trochę plotkuje.",
        "Mój słuch wydaje się równie dobry, jak słuch większości ludzi.",
        "Niektóre osoby z mojej rodziny mają nawyki, które przeszkadzają mi i bardzo mnie denerwują.",
        "Czasami mam poczucie, że mogę podejmować decyzje z niezwykłą łatwością.",
        "Chciałbym/chciałabym należeć do kilku klubów.",
        "Prawie nigdy nie odczuwam łomotania serca i rzadko brakuje mi tchu.",
        "Lubię rozmawiać o seksie.",
        "Lubię zwiedzać miejsca, w których nigdy przedtem nie byłem/nie byłam.",
        "Porwał mnie styl życia oparty na obowiązkach i odtąd ściśle się nim kieruję.",
        "Często stawałem na drodze przedsięwzięciom podejmowanym przez innych ludzi, nie dlatego, że było warto, lecz dla samej zasady.",
        "Łatwo się wściekam i szybko uspokajam.",
        "Byłem/byłam dość niezależny/niezależna i wolny/wolna od zasad panujących w mojej rodzinie.",
        "Dużo rozpamiętuje.",
        "Ktoś próbował mnie obrabować.",
        "Prawie wszyscy moi krewni są ze mną solidarni.",
        "Miewam okresy tak wielkiego niepokoju, że nie mogę usiedzieć w miejscu.",
        "Doznałem/doznałam rozczarowania w miłości.",
        "Nigdy nie przejmuję się swoim wyglądem.",
        "Często marzę o rzeczach, które, najlepiej zachować dla siebie.",
        "Dzieciom powinno się przekazywać wszystkie podstawowe fakty na temat seksu.",
        "Sądzę, że nie jestem bardziej nerwowy/nerwowa niż większość ludzi.",
        "Bóle miewam rzadko lub wcale.",
        "Moj sposób postępowania bywa źle rozumiany przez innych.",
        "Czasami bez żadnego powodu, albo nawet wtedy, gdy sprawy idą źle, czuję się szczęśliwy/szczęśliwa, jak „w siódmym niebie”.",
        "Nie potępiam ludzi za to, że próbują brać z życia, ile się da.",
        "Są ludzie, którzy próbują wykraść moje myśli.",
        "Miewałem/miewałam chwile nieświadomości, w których przestawałem/przestawałam coś robić i traciłem/traciłam orientację w tym, co się wokół mnie działo.",
        "Potrafię żyć w przyjaźni z ludźmi robiącymi rzeczy które uważam za złe.",
        "Lubię przebywać wśród ludzi, którzy robią sobie kawały.",
        "Czasami głosuję w wyborach na ludzi, o których bardzo mało wiem.",
        "Trudno jest mi się do czegoś zabrać.",
        "Uważam, że jestem człowiekiem potępionym.",
        "W szkole miałem/miałam trudności z  nauką.",
        "Gdybym był/była artystą/artystką, chciałbym/chciałabym rysować kwiaty.",
        "Nie przejmuję się tym, że nie wyglądam lepiej.",
        "Łatwo się pocę, nawet w chłodne dni.",
        "Jestem pełen/pełna wiary w siebie.",
        "Czasami nie mogłem/nie mogłam powstrzymać się od przywłaszczenia sobie czegoś lub kradzieży w sklepie.",
        "Bezpieczniej jest nie ufać nikomu.",
        "Raz na tydzień lub częściej bywam bardzo podekscytowany/podekscytowana.",
        "Kiedy jestem w grupie ludzi, mam trudność ze znalezieniem właściwego tematu do rozmowy.",
        "Coś ekscytującego prawie zawsze potrafi mnie wyciągnąć ze stanu przygnębienia.",
        "Kiedy wychodzę z domu, nie martwię się o to, czy przekręciłem/przekręciłam klucz w zamku i zamknąłem/zamknęłam okna.",
        "Uważam, że moje grzechy są niewybaczalne.",
        "Odczuwam zdrętwienie w jednym lub kilku miejscach na skórze.",
        "Nie obwiniam nikogo za wykorzystywanie ludzi, którzy sami się a o to proszą.",
        "Mój wzrok jest ciągle równie dobry, jak był.",
        "Czasami tak mi się podobał spryt niektórych przestępców, że chciałem/chciałam, by to, co zrobili, uszło im na sucho.",
        "Często miałem/miałam wrażenie, że obcy ludzi krytycznie na mnie patrzą.",
        "Wszystko smakuje tak samo.",
        "Wypijam codziennie niezwykle dużo wody.",
        "Większość ludzi nawiązuje przyjaźnie, ponieważ mogą im się one do czegoś przydać.",
        "Rzadko słyszę szum lub dzwonienie w uszach.",
        "Czasami czuję nienawiść do członków mojej rodziny, których w zasadzie kocham.",
        "Gdybym był/była dziennikarzem/dziennikarką, bardzo chciałbym/chciałabym zajmować się wiadomościami sportowymi.",
        "Mogę spać w dzień, ale nie w nocy.",
        "Jestem pewien/pewna, że ludzie o mnie rozmawiają.",
        "Czasami śmieję się z nieprzyzwoitych i dowcipów.",
        "Mam bardzo mało lęków w porównaniu z moimi znajomymi.",
        "W grupie nie czułbym/czułabym się skrępowany/skrępowana, gdyby wezwano mnie do rozpoczęcia dyskusji lub wyrażenia opinii w dobrze mi znanej kwestii.",
        "Jestem zawsze pełen/pełna obrzydzenia wobec prawa, gdy przestępca wychodzi na wolność dzięki argumentom sprytnego prawnika.",
        "Nadużywałem/nadużywałam alkoholu.",
        "Na ogół nie odzywam się do ludzi, dopóki oni nie odezwą się do mnie.",
        "Nigdy nie byłem/nie byłam na bakier z prawem.",
        "Miewam okresy, kiedy jest mi niezwykle wesoło bez żadnego szczególnego powodu.",
        "Chciałbym/chciałabym, żeby nie niepokoiły mnie myśli o seksie.",
        "Jeśli kilka osób znajdzie się w kłopotach, najlepszym wyjściem jest uzgodnienie wersji wydarzeń i trzymanie się jej.",
        "Widok cierpiących zwierząt niespecjalnie mi przeszkadza.",
        "Myślę, że odczuwam silniej niż większość ludzi.",
        "Nigdy w życiu nie lubiłem/nie lubiłam bawić się lalkami.",
        "Życie jest dla mnie przeważnie wysiłkiem.",
        "Jestem tak drażliwy/drażliwa w pewnych sprawach, że nie mogę o nich rozmawiać.",
        "W szkole trudno mi było zabierać głos przed całą klasą.",
        "Kocham moja matkę lub (jeśli twoja matka nie żyje): Kochałem/kochałam moją matkę.",
        "Nawet gdy jestem z ludźmi, czuję się przeważnie samotny/samotna.",
        "Otrzymuję tyle współczucia, na ile zasługuję.",
        "Odmawiam udziału w pewnych grach, ponieważ nie jestem w nich dobry/dobra.",
        "Wydaje mi się, że nawiązuję przyjaźnie mniej więcej tak samo szybko, jak inni.",
        "Nie lubię mieć ludzi wokół siebie.",
        "Powiedziano mi, że chodzę we śnie.",
        "Osoba, która stwarza pokusę, zostawiając coś cennego bez ochrony, jest prawie tak samo winna kradzieży jak ten, kto jej dokonuje.",
        "Myślę, że prawie każdy skłamałby, żeby uniknąć kłopotów.",
        "Jestem bardziej wrażliwy/wrażliwa niż większość ludzi.",
        "Większość ludzi w duchu nie lubi zadawać sobie trudu, żeby pomóc innym.",
        "Wiele z moich snów dotyczy seksu.",
        "Moi rodzice i rodzina widzą we mnie więcej wad niż powinni.",
        "Łatwo się peszę.",
        "Martwię się o pieniądze i interesy.",
        "Nigdy nie byłem/nie byłam w nikim zakochany/zakochana.",
        "Przeraża mnie to, co robią niektóre osoby z mojej rodziny.",
        "Prawie nigdy nie śnię.",
        "Często dostaję czerwonych plam na szyi.",
        "Nigdy nie doznałem/nie doznałam paraliżu czy niezwykłego osłabienia mięśni.",
        "Czasami mój głos zmienia się czy zanika, pomimo że nie jestem przeziębiony/przeziębiona.",
        "Matka lub ojciec często zmuszali mnie do posłuszeństwa, nawet gdy uważałem/uważałam to za nierozsądne.",
        "Czasami czuję dziwne zapachy.",
        "Nie potrafię skupić się na jednej rzeczy.",
        "Mam powód, aby czuć się zazdrosnym/zazdrosną o jednego lub paru członków mojej rodziny.",
        "Prawie zawsze niepokoję się o coś lub o kogoś.",
        "Łatwo tracę cierpliwość wobec ludzi.",
        "Przeważnie czuję, że wołałbym/wołałabym nie żyć.",
        "Czasami jestem tak pobudzony/pobudzona, że trudno mi zasnąć.",
        "Z cała pewnością miałem/miałam więcej powodów do zmartwień niż mi się należało.",
        "Nikogo za bardzo nie obchodzi, co się z tobą stanie.",
        "Czasami słyszę tak dobrze, że aż mnie to niepokoi.",
        "Natychmiast zapominam, co ludzie do mnie mówią.",
        "Zazwyczaj muszę się zatrzymać i pomyśleć, zanim coś zrobię, nawet gdy chodzi o drobne sprawy.",
        "Często przechodzę na drugą stronę ulicy, aby uniknąć spotkania z kimś, kogo zobaczyłem/zobaczyłam.",
        "Często mam poczucie nierealności.",
        "W gazetach interesujące są tylko komiksy.",
        "Mam nawyk liczenia nieistotnych rzeczy, takich jak żarówki w napisach świetlnych itp.",
        "Nie mam wrogów, którzy naprawdę chcieliby mnie skrzywdzić.",
        "Mam się na baczności wobec ludzi, którzy są bardziej przyjacielscy niż mógłbym/mogłabym się spodziewać.",
        "Mam dziwne i osobliwe myśli.",
        "Staję się niespokojny/niespokojna i rozstrojony/rozstrojona, kiedy muszę na krótko wyjechać z domu.",
        "Zazwyczaj oczekuję, że powiedzie mi się w tym, co robię.",
        "Kiedy jestem sam/sama, słyszę dziwne rzeczy.",
        "Zdarzało mi się bać rzeczy lub ludzi, o których wiedziałem/wiedziałam, że nie mogą zrobić mi krzywdy.",
        "Nie boję się wejść samemu/samej do pokoju, w którym rozmawiają zgromadzone tam wcześniej osoby.",
        "Boje się używać noża lub jakiegokolwiek ostrego czy ostro zakończonego  przedmiotu.",
        "Czasem sprawia mi przyjemność ranienie osób, które kocham.",
        "Łatwo mogę sprawić, że ludzie zaczynają się mnie bać, i czasami robię to dla zabawy.",
        "Mam większe kłopoty z koncentracją niż inni.",
        "Kilka razy dałem/dałam za wygraną i nie zrobiłem/nie zrobiłam czegoś, bo zbyt nisko oceniłem/oceniłam swoje zdolności.",
        "Przychodzą mi na myśl złe, straszne słowa i nie mogę się od nich uwolnić.",
        "Czasami jakaś nieważna myśl chodzi mi po głowie i dręczy całymi dniami.",
        "Prawie codziennie zdarza się coś, co mnie przeraża.",
        "Czasami jestem pełen/pełna energii.",
        "Mam skłonność do przejmowania się wszystkim.",
        "Czasami czułem/czułam przyjemność, kiedy ranił mnie ktoś, kogo kochałem/kochałam.",
        "Ludzie mówią o mnie rzeczy obraźliwe i wulgarne.",
        "Czuję się niespokojny/niespokojna, przebywając w zamkniętych pomieszczeniach.",
        "Nie jestem szczególnie nieśmiały/nieśmiała.",
        "Ktoś ma kontrolę nad moim umysłem.",
        "Na przyjęciach prędzej będę siedział/siedziała sam/sama lub z jedną tylko   osobą, niż przyłączę się do grupy.",
        "Ludzie często mnie rozczarowują.",
        "Czasami czułem/czułam, że problemy piętrzyły się tak, że nie mogłem/mogłam ich pokonać.",
        "Uwielbiam chodzić gdzieś potańczyć.",
        "Zdarzają się okresy, kiedy mój umysł wydaje się pracować wolniej niż zazwyczaj.",
        "Często rozmawiam z nieznajomymi w pociągu, autobusie itp.",
        "Lubię dzieci.",
        "Lubię grać, choćby o małe stawki.",
        "Gdyby dano mi szansę, mógłbym/mogłabym zrobić rzeczy, które przyniosłyby światu wielką korzyść.",
        "Często spotykałem/spotykałam ludzi uważanych za ekspertów, którzy nie byli lepsi ode mnie.",
        "Kiedy słyszę o sukcesie osoby, którą dobrze znam, czuję się jak nieudacznik.",
        "Często sobie myślę: „Chciałbym/chciałabym być znowu dzieckiem”.",
        "Jestem najbardziej szczęśliwy/szczęśliwa, gdy jestem sam/sama.",
        "Gdybym miał okazję, mógłbym/mogłabym być dobrym przywódcą.",
        "Sprośne historie wprawiają mnie w zażenowanie.",
        "Na ogół ludzie domagają się więcej poszanowania dla swoich własnych praw, niż są go skłonni przyznać innym.",
        "Lubię spotkania towarzyskie, bo mogę być z innymi ludźmi.",
        "Staram się zapamiętywać ciekawe historie, aby przekazywać je innym.",
        "Raz czy parę razy w życiu czułem/czułam, że ktoś zmusza mnie do robienia czegoś, hipnotyzując mnie.",
        "Odłożenie, choćby na krótki czas, zadania, którego się podjąłem/podjęłam, jest dla mnie trudne.",
        "Dość często bywam niewtajemniczony/niewtajemniczona w płotki i rozmowy grupy, do której należę.",
        "Często stwierdzałem/stwierdzałam, że ludzie zazdroszczą mi dobrych pomysłów tylko dlatego, że sami na nie wcześniej nie wpadli.",
        "Lubię atmosferę podniecenia w tłumie.",
        "Nie mam nic przeciwko poznawaniu obcych ludzi.",
        "Ktoś próbował wpływać na mój umysł.",
        "Pamiętam, że udawałem/udawałam chorego/chorą, żeby się od czegoś wykręcić.",
        "Moje troski wydają się znikać, kiedy znajduję się w tłumie pełnych wigoru znajomych.",
        "Kiedy cos idzie źle, mam ochotę szybko się poddać.",
        "Lubię dać ludziom do zrozumienia moje stanowisko wobec różnych spraw.",
        "Miewałem/miewałam okresy, w których byłem/byłam tak pełny/pełna wigoru, że przez kilka dni z rzędu sen nie wydawał mi się potrzebny.",
        "Gdy tylko jest to możliwe, unikam przebywania w tłumie.",
        "Wzdragam się przed stawieniem czoła kryzysowi czy trudnościom.",
        "Jestem skłonny/skłonna rezygnować z tego, co chcę zrobić, jeśli inni sądzą, że nie warto tego robić.",
        "Lubię przyjęcia i spotkania towarzyskie.",
        "Często żałuję, że nie należę do płci przeciwnej.",
        "Niełatwo mnie rozzłościć.",
        "W przeszłości zrobiłem/zrobiłam parę złych rzeczy, o których nigdy nikomu nie mówię.",
        "Większość ludzi używa niezbyt uczciwych sposobów, aby zdobyć w życiu przewagę.",
        "Denerwuję się, kiedy ludzie zadają mi osobiste pytania.",
        "Nie sądzę, żebym mógł/mogła zaplanować własną przyszłość.",
        "Nie jestem zadowolony/zadowolona z tego, jaki/jaka jestem.",
        "Złości mnie, kiedy przyjaciele lub rodzina radzą mi, jak mam przeżyć moje własne życie.",
        "Kiedy byłem/byłam dzieckiem, często dostawałem/dostawałam w skórę.",
        "Przeszkadza mi, kiedy ludzie mówią o mnie miłe rzeczy.",
        "Nie lubię wysłuchiwać, jak ludzie wygłaszają swoje poglądy na życie.",
        "Często dochodzi do poważnej różnicy zdań między mną a moimi bliskimi.",
        "Kiedy coś idzie naprawdę źle, wiem, że mogę liczyć na pomoc rodziny.",
        "Gdy byłem/byłam dzieckiem, lubiłem/lubiłam bawić się „w dom”.",
        "Nie boję się ognia.",
        "Czasami trzymałem/trzymałam się z dala od kogoś w obawie, że powiem lub zrobię coś, czego mógłbym/mogłabym później żałować.",
        "Moje prawdziwe uczucia potrafię wyrazić tylko wtedy, gdy piję.",
        "Bardzo rzadko miewam okresy przygnębienia.",
        "Często mówią mi, że jestem „w gorącej wodzie kąpany/kąpana”.",
        "Chciałbym/chciałabym móc przestać martwić się, że to, co powiedziałem/powiedziałam, mogło zranić uczucia innych ludzi.",
        "Nie czuję się w stanie powiedzieć nikomu wszystkiego o sobie.",
        "Jedną z rzeczy, których się boję, są błyskawice.",
        "Lubię trzymać ludzi w niepewności co do tego, co zamierzam zaraz zrobić.",
        "Moje płany często wydawały się tak najeżone trudnościami, że musiałem/musiałam z nich rezygnować.",
        "Boję się przebywać sam/sama w ciemności.",
        "Często miewam niemiłe uczucie bycia źle zrozumianym/zrozumianą, gdy próbuję powstrzymać kogoś od popełnienia błędu.",
        "Przerażają mnie wichury.",
        "Często proszę łudzi o radę.",
        "Przyszłość jest zbyt niepewna, aby robić poważne plany.",
        "Często, nawet gdy wszystko dobrze mi idzie, mam poczucie, ze na niczym mi nie zależy.",
        "Nie odczuwam łęku przed wodą.",
        "Często muszę „przespać się ze sprawą”, zanim podejmę decyzję.",
        "Często zdarza się, że ludzie nie rozumieją moich intencji, kiedy próbuję im pomóc i działać dla ich dobra.",
        "Nie mam kłopotów z przełykaniem.",
        "Zazwyczaj jestem spokojny/spokojna i niełatwo mnie zdenerwować.",
        "Z pewnością bawiłoby mnie pokonywanie przestępców ich własną bronią.",
        "Zasługuję na surową karę za moje grzechy.",
        "Zwykle tak silnie przeżywam rozczarowania, że nie mogę ich wyrzucić z pamięci.",
        "Przeszkadza mi, kiedy ktoś obserwuje mnie przy pracy, nawet gdy wiem, że potrafię ją dobrze wykonać.",
        "Kiedy ktoś próbuje wepchnąć się przede mnie w kolejce, często irytuje mnie to do tego stopnia, że zwracam mu uwagę.",
        "Czasami myślę, że wcale nie jestem dobry/dobra.",
        "Kiedy byłem/byłam młody/młoda, często nie szedłem/szłam do szkoły, choć powinienem/powinnam.",
        "Jedna lub więcej osób z mojej rodziny to osoby bardzo nerwowe.",
        "Czasami musiałem/musiałam być szorstki/szorstka w stosunku do osób, które były nieuprzejme lub denerwujące.",
        "Dość często martwię się nieszczęściami, które mogą się wydarzyć.",
        "Mam zdecydowane poglądy polityczne.",
        "Chciałbym/chciałabym być kierowcą wyścigowym.",
        "Nie ma niczego złego w obchodzeniu prawa, jeśli się go nie łamie.",
        "Są ludzie, których nie lubię do tego stopnia, że jestem w głębi duszy zadowolony/zadowolona, gdy dostają za swoje.",
        "Denerwuje mnie, gdy muszę czekać.",
        "Jestem skłonny/skłonna zrezygnować z czegoś, co chcę zrobić, gdy inni sądzą, że nie zabieram się do tego we właściwy sposób.",
        "Kiedy byłem/byłam młody/młoda, uwielbiałem/uwielbiałam być czymś podekscytowany/podekscytowana.",
        "Często jestem skłonny/skłonna zrobić coś nie po swojej myśli, aby zdobyć przewagę nad kimś, kto mi się sprzeciwił.",
        "Niepokoją mnie ludzie, którzy przyglądają mi się na ulicy, w sklepie, itp.",
        "Mężczyzna, z którym miałem/miałam najwięcej do czynienia w dzieciństwie (np, mój ojciec, ojczym itp.), był wobec mnie bardzo surowy.",
        "Lubiłem/lubiłam grać w klasy i skakać przez skakankę.",
        "Nigdy nie miałem/miałam zwidów.",
        "Kilkakrotnie zmieniałem/zmieniałam zdanie na temat swojej życiowej drogi zawodowej.",
        "Nigdy nie biorę lekarstw ani pigułek nasennych bez zalecenia lekarza.",
        "Często jest mi przykro, że jestem taki/taka drażliwy/drażliwa i zrzędliwy/zrzędliwa.",
        "W szkole miewałem/miewałam na ogół złe oceny z zachowania.",
        "Fascynuje mnie ogień.",
        "Przyparty/przyparta do muru, mówię tylko tę część prawdy, która mi prawdopodobnie nie zaszkodzi.",
        "Gdybym wpadł/wpadła w kłopoty wraz z kilkoma kolegami, którzy byliby tak samo winni jak ja, raczej wziąłbym/wzięłabym całą winę na siebie, niż ich wydał/wydala.",
        "Często boję się ciemności.",
        "Mężczyzna w obecności kobiety i zazwyczaj myśli o rzeczach związanych z jej płcią.",
        "Wobec ludzi, których usiłuję poprawić czy udoskonalić, jestem zazwyczaj bardzo bezpośredni/bezpośrednia.",
        "Boję się na samą myśl o trzęsieniu ziemi.",
        "Łatwo daję się w stu procentach przekonać do dobrego pomysłu.",
        "Zazwyczaj sam/sama rozpracowuje problemy, zamiast prosić kogoś, by pokazał mi, jak to zrobić.",
        "Boję się, że mógłbym/mogłabym się znaleźć w szafie lub innym ciasnym pomieszczeniu.",
        "Muszę przyznać, że zdarza mi się czasami zamartwiać ponad miarę czymś, co w rzeczywistości nie ma znaczenia.",
        "Nie próbuję ukrywać przed ludźmi swojej złej opinii na ich temat lub politowania dla nich, tak, by nie wiedzieli, co czuję.",
        "Jestem osobą bardzo nerwową.",
        "W pracy często podlegałem/podlegałam ludziom, którzy potrafili tak kierować sprawami, by zbierać pochwały za dobrze wykonaną pracę, a porażkami obciążać podwładnych.",
        "Jestem tak powściągliwy/powściągliwa, że czasami trudno mi walczyć o swoje prawa.",
        "Brud budzi we mnie strach i wstręt.",
        "W marzeniach prowadzę życie, o którym nie mówię innym ludziom.",
        "Niektóre osoby z mojej rodziny mają wybuchowe charaktery.",
        "Niczego nie potrafię zrobić dobrze.",
        "Często czuję się winny/winna, bo udaję że jest mi z jakiegoś powodu bardziej przykro niż ma to miejsce w rzeczywistości.",
        "Z zasady mocno bronię własnych poglądów.",
        "Nie boję się pająków.",
        "Moja przyszłość wydaje mi się beznadziejna.",
        "Członkowie mojej rodziny i bliscy krewni pozostałą ze sobą w dobrych stosunkach.",
        "Chciałbym/chciałabym nosić drogie ubrania.",
        "Nawet jeśli podjąłem/podjęłam decyzję w jakiejś sprawie, ludzie mogą ją z łatwością zmienić.",
        "Pewne zwierzęta budzą we mnie niepokój.",
        "Jestem równie wytrzymały/wytrzymała na ból, jak inni.",
        "Kilka razy zdarzyło mi się być ostatnim/ostatnią, który/która dawał/dawała za wygraną.",
        "Złoszczę się, kiedy ludzie mnie pośpieszają.",
        "Nie boję się myszy.",
        "Kilka razy w tygodniu mam poczucie, jakby zaraz miało stać się coś strasznego.",
        "Przez znaczną część czasu czuję się zmęczony/zmęczona.",
        "Lubię naprawiać zamki w drzwiach.",
        "Czasami jestem pewien, że inni ludzie są w stanie powiedzieć, co myślę.",
        "Lubię czytać teksty poświęcone nauce.",
        "Boję się być sam/sama na otwartej przestrzeni.",
        "Czasami czuję się tak, jakbym miał/miała się rozpaść na kawałki.",
        "Wielu ludzi ma na sumieniu złe zachowania seksualne.",
        "Często odczuwałem/odczuwałam lęk w środku nocy.",
        "Strasznie dokucza mi to, że zapominam, gdzie coś kładę.",
        "Osobą, do której byłem/byłam najbardziej przywiązany/przywiązana i którą najbardziej podziwiałem/ podziwiałam w dzieciństwie, była kobieta (matka, siostra, ciotka lub inna kobieta).",
        "Wolę historie przygodowe niż romanse.",
        "Często mieszam się i zapominam, co chciałem/chciałam powiedzieć.",
        "Jestem bardzo niezdarny/niezdarna i niezręczny/niezręczna.",
        "Bardzo lubię uprawiać ostre sporty (takie jak futbol amerykański czy piłka nożna).",
        "Nienawidzę całej mojej rodziny.",
        "Niektórzy ludzie uważała, że trudno jest mnie poznać.",
        "Większość wolnego czasu spędzam sam/sama.",
        "Kiedy ludzie robią coś, co mnie złości, daję im do zrozumienia, co w związku z tym czuję.",
        "Zazwyczaj ciężko mi podjąć decyzję co zrobić.",
        "Ludzie nie uważają mnie za osobę atrakcyjną.",
        "Ludzie nie są dla mnie zbyt mili.",
        "Często czuję, że nie jestem tak dobry/dobra, jak inni.",
        "Jestem bardzo uparty/uparta.",
        "Palenie marihuany sprawiało mi przyjemność.",
        "Choroba psychiczna jest oznaką słabości.",
        "Mam problem z narkotykami lub alkoholem.",
        "Duchy i zjawy mogą mieć dobry łub zły wpływ na ludzi.",
        "Kiedy muszę podjąć ważną decyzję, czuje się bezradny/bezradna.",
        "Zawsze staram się być miły/miła, nawet jeśli inni są zdenerwowani czy krytyczni.",
        "Kiedy mam jakiś problem, pomaga mi omówienie go z kimś.",
        "Moje główne cele życiowe znajdują się w zasięgu moich możliwości.",
        "Sądzę, że ludzie powinni zachowywać swoje problemy osobiste dla siebie.",
        "Nie odczuwam ostatnio silnego napięcia nim stresu.",
        "Myślenie o dokonywaniu zmian w moim życiu budzi we mnie duży niepokój.",
        "Przyczyną moich największych problemów jest zachowanie kogoś mi bliskiego.",
        "Nie cierpię chodzić do lekarzy, nawet jeśli jestem chory/chora.",
        "Choć nie jestem zadowolony/zadowolona ze swojego życia, nie mogę teraz nic na to poradzić.",
        "Przegadanie z kimś problemów i zmartwień jest często bardziej pomocne niż zażywanie lekarstw czy proszków.",
        "Mam parę naprawdę szkodliwych nawyków.",
        "Kiedy trzeba rozwiązać jakiś problem, zazwyczaj zdaję się na innych.",
        "Dostrzegam u siebie kilka wad, których nie będę w stanie zmienić.",
        "Mam już tak dosyć tego, co muszę robić każdego dnia, że chcę to wszystko rzucić.",
        "Zastanawiałem/zastanawiałam się ostatnio nad popełnieniem samobójstwa.",
        "Często reaguję rozdrażnieniem, kiedy ludzie przeszkadzają mi w pracy.",
        "Często czuję, że potrafię czytać w myślach innych ludzi.",
        "Konieczność podejmowania ważnych decyzji sprawia, że się denerwuję.",
        "Inni mówią mi, że zbyt szybko jem.",
        "Przynajmniej raz w tygodniu upijam się lub odurzam się narkotykami.",
        "Doznałem/doznałam w swoim życiu tragicznej straty i wiem, że nigdy jej nie przeboleję.",
        "Czasami robię się tak zły/zła i zdenerwowany/zdenerwowana, że nie wiem, co mnie nachodzi.",
        "Kiedy ludzie proszą mnie, abym coś zrobił/zrobiła, bardzo ciężko jest mi odmówić.",
        "Nigdy nie bywam bardziej szczęśliwy/szczęśliwa niż wtedy, gdy jestem sam/sama.",
        "Moje życie jest puste i bezsensowne.",
        "Jest mi trudno utrzymać się w pracy.",
        "Popełniłem/popełniłam w życiu wiele poważnych błędów.",
        "Jestem zły/zła na siebie, że tak bardzo ulegam innym ludziom.",
        "Ostatnio wiele myślałem/myślałam o tym, żeby się zabić.",
        "Lubię podejmować decyzje i przydzielać pracę innym.",
        "Wiem, że nawet gdybym nie miał/nie miała rodziny, zawsze będzie ktoś, kto zatroszczy się o mnie.",
        "Nienawidzę czekania w kolejce do kina, restauracji czy na imprezę sportową.",
        "Nikt o tym nie wie, ale próbowałem/próbowałam się zabić.",
        "Wszystko wokół mnie dzieje się zbyt szybko.",
        "Wiem, że jestem dla innych ciężarem.",
        "Po złym dniu potrzebuję zwykle paru drinków, aby się wyluzować.",
        "Znaczna część moich kłopotów jest spowodowana pechem.",
        "Czasami wydaje się, że nie mogę przestać mówić.",
        "Czasami celowo kaleczę się lub ranię, nie wiedząc, dlaczego.",
        "Pracuję do późna, mimo że moje obowiązki tego nie wymagają.",
        "Zazwyczaj czuję się lepiej, kiedy się porządnie wypłaczę.",
        "Zapominam, gdzie kładę różne rzeczy.",
        "Gdybym mógł/mogła przeżyć swoje życie ponownie, nie zmieniłbym/nie zmieniłabym w nim wiele.",
        "Bardzo mnie irytuje, gdy ludzie, na których liczę, nie wykonują swojej pracy na czas.",
        "Jeśli się czymś zdenerwuję, jestem pewien/pewna, że rozboli mnie głowa.",
        "Lubię stawiać twarde warunki.",
        "Większość mężczyzn od czasu do czasu jest niewierna swoim żonom.",
        "Ostatnio straciłem/straciłam chęci, by zmierzyć się ze swoimi problemami.",
        "Kiedy piłem/piłam, wpadałem/wpadałam w gniew i rozbijałem/rozbijałam meble lub naczynia.",
        "Najlepiej pracuję wtedy, gdy mam wyznaczony ostateczny termin.",
        "Bywałem/bywałam na kogoś tak zły/zła, że czułem/czułam się jakbym miał/miała zaraz wybuchnąć.",
        "Czasem nachodzą mnie okropne myśli na temat mojej rodziny.",
        "Ludzie mówią mi, że mam problem z alkoholem, ale ja się z tym nie zgadzam.",
        "Zawsze mam za mało czasu, żeby doprowadzić rzeczy do końca.",
        "Ostatnio moje myśli coraz bardziej kierują się ku śmierci i życiu pozagrobowemu.",
        "Często przechowuję rzeczy, których prawdopodobnie nigdy nie użyję.",
        "Czasami bywałem/bywałam tak zły/zła, że raniłem/raniłam kogoś fizycznie.",
        "Cokolwiek ostatnio robię, mam wrażenie, że jestem poddawany/poddawana próbie.",
        "Obecnie mam bardzo mało wspólnego z moimi krewnymi.",
        "Czasami wydaje mi się, że słyszę swoje myśli wypowiadane głośno.",
        "Kiedy jestem smutny/smutna, odwiedziny u przyjaciół zawsze wyciągają mnie z dołka.",
        "Wydaje mi się, że wiele z tego, co mi się teraz przydarza, przydarzało mi się już wcześniej.",
        "Kiedy życie staje się trudne, mam ochotę po prostu się poddać.",
        "Nie jestem w stanie wejść sam/sama do ciemnego pokoju, nawet we własnym domu.",
        "Bardzo martwię się o pieniądze.",
        "Mężczyzna powinien być głową rodziny.",
        "Jedynym miejscem, w którym czuję się odprężony/odprężona, jest mój własny dom.",
        "Ludzie, z którymi pracuję, nie okazują zrozumienia dla moich problemów.",
        "Jestem zadowolony/zadowolona z tego, ile zarabiam.",
        "Zazwyczaj mam dość energii, by wykonać swoją pracę.",
        "Trudno jest mi przyjmować komplementy.",
        " W większości małżeństw co najmniej jedno z partnerów jest nieszczęśliwe.",
        "Prawie nigdy nie tracę samokontroli.",
        "Ostatnio wiele wysiłku kosztuje mnie zapamiętanie tego, co ktoś do mnie mówi.",
        "Tym co cierpi, kiedy jestem smutny/smutna lub przygnębiony/przygnębiona, jest moja praca.",
        "Większość par małżeńskich nie okazuje sobie nawzajem zbyt wiele uczucia."
    };
}

#endif // MMPI2_HPP
